### ISSUE TITLE
Can it read states?

### ISSUE THREAD

**Issue by piertjep** [PhoenixR49/hass-huggingchat-conversation#1]
Is it possible to read the states of the entities?

**Comment by PhoenixR49** [comment]
Sorry to disappoint you, but this integration doesn't create any entities. It just creates a conversational agent to create an assistant that supports [HuggingChat](https://huggingface.co/chat/).

**Comment by PhoenixR49** [comment]
Ok, I misunderstood your question @piertjep! In reality, entities can only be read if they are assigned to rooms (or if you modify your prompt to include them).

I'm currently working on a new update that would allow devices to be controlled via the HuggingChat wizard.

**Comment by shon4840** [comment]
> Ok, I misunderstood your question @piertjep! In reality, entities can only be read if they are assigned to rooms (or if you modify your prompt to include them).
> 
> I'm currently working on a new update that would allow devices to be controlled via the HuggingChat wizard.

how soon can we expect this function to be added?

**Comment by PhoenixR49** [comment]
Hi @shon4840! I haven't started adding this feature to the integration yet. I'm don't know when it will be ready or if it will ever be ready...
However, if you have an idea of how to do it and would like to contribute to the project, you can write a pull request of your changes. 

Have a nice day ;)

**Comment by shon4840** [comment]
> Hi @shon4840! I haven't started adding this feature to the integration yet. I'm don't know when it will be ready or if it will ever be ready... However, if you have an idea of how to do it and would like to contribute to the project, you can write a pull request of your changes.
> 
> Have a nice day ;)

Hi! There is an ollama integration for home assistant(https://github.com/home-assistant/core/tree/dev/homeassistant/components/ollama) I think they won't mind if you borrow their code to implement this feature I am not a programmer myself and unfortunately I don't know how to program
