### ISSUE TITLE
I have successfully modified the integration so that it works again

### ISSUE THREAD

**Issue by richieam93** [PhoenixR49/hass-huggingchat-conversation#11]
Hello,

I have successfully modified the integration so that it works again. The chatbot is now running without any issues.

During the adjustment, I also expanded the search function, as the original problem existed before the implementation of the search function. The current configuration is compatible with the latest Home Assistant software.

Please replace all 5 files to activate the new configuration. The const.py file has also been updated to resolve an issue with Home Assistant.

Make sure to reconfigure your language settings.

I intended to upload a ZIP file, but this was unfortunately not possible. Therefore, I have included all the scripts below:

__init__.py
config_flow.py
const.py
manifest.json
strings.json
Language Folder
If you have any difficulties integrating the search function yourself, I am happy to assist you further.

Best regards,

`
![image](https://github.com/user-attachments/assets/e31aa27f-3d17-42c6-ad4b-e9fd078c8a39)
[skript.json](https://github.com/user-attachments/files/17610812/skript.json)

**Comment by PhoenixR49** [comment]
Hi @richieam93. Thank you very much for your modification!
Could you create a pull-request with the linked modifications? It would help me a lot for proofreading and checking the code

Thanks again and have a nice evening ;)

**Comment by PhoenixR49** [comment]
Hi @richieam93. Thank you very much for your modification!
Could you create a pull-request with the linked modifications? It would help me a lot for proofreading and checking the code

Thanks again and have a nice evening ;)
