### ISSUE TITLE
Bug report: 

### ISSUE THREAD

**Issue by Elarion245** [PhoenixR49/hass-huggingchat-conversation#14]
**Describe the bug**
I wanted to give it a try, so I installed the integration and put in the hugging face credentials.
When configuring the integration, the following is reported:

![IMG_20241113_222725](https://github.com/user-attachments/assets/6e40930e-ae25-4699-8ad1-7e8ad181788f)

Do I need to do anything after registering in HuggingFace for the error to disappear?

**To Reproduce**
Install via HACS, enter credentials and setup voice pipeline 

**Expected behavior**
I don't know, but no error

**Screenshots**
See above

**Environment:**
 - Home Assistant version 2024.11
 - Version 1.3.5

**Comment by PhoenixR49** [comment]
This is due to the same problem as issue #13

**Comment by PhoenixR49** [comment]
Please update to [v1.3.6](https://github.com/PhoenixR49/hass-huggingchat-conversation/releases/tag/v1.3.6)
