### ISSUE TITLE
all umlauts are displayed as follows Ã¤, Ã¶, and Ã¼.

### ISSUE THREAD

**Issue by richieam93** [PhoenixR49/hass-huggingchat-conversation#2]
Good day

I've had a problem for about 3 days that the Assist can no longer write umlauts.
On the website https://huggingface.co/chat/conversation/ the umlauts work for every model.

Could this be a problem with UTF-8 (all umlauts are displayed as follows Ã¤, Ã¶, and Ã¼.) but must be ä,ö,ü

Thank you very much for your help, I think this is a good project.

![umlaute01](https://github.com/PhoenixR49/hass-huggingchat-conversation/assets/91011752/fb8fc1dc-728c-4002-ab39-b5f08c9def64)
![umlaute02](https://github.com/PhoenixR49/hass-huggingchat-conversation/assets/91011752/aee8bae8-7bee-4bc7-9e0b-e781ce022885)

**Comment by PhoenixR49** [comment]
First of all, tank you for your comment!

Indeed, this problem may be due to a recent Home Assistant update - it's a UTF-8 encoding error. I'll try to fix it over the weekend.
In the meantime, enjoy the integration!

**Comment by richieam93** [comment]
Thank you very much for your time

I'll be happy to test it.

Of all the Local AI Hacs functions, I find this one to work the fastest.

What is the status regarding the control of the lamps and switches?

For testing purposes, I have already made a request to home-llm regarding an integration of your project.
https://github.com/acon96/home-llm/issues/42

**Comment by richieam93** [comment]
It works again

Thank you very much for the editing.

![umlaute03](https://github.com/PhoenixR49/hass-huggingchat-conversation/assets/91011752/ddf99311-1341-4c1f-abf0-5a322906c952)
