### ISSUE TITLE
Login currently not working with Hugging Face

### ISSUE THREAD

**Issue by laberning** [PhoenixR49/hass-huggingchat-conversation#6]
**Describe the bug**
Currently, login with Hugging Face will throw an exception `Exception: Something went wrong!`

**To Reproduce**
1. Install the Integration (i.e. via HACS)
2. Add the Integration
3. Click Configure and Enter Credentials
4. Login will report wrong credentials
5. Logs will report `Exception: Something went wrong!`

**Expected behavior**
Login should succeed

**Additional context**
The reason for the Problem seems to be this issue with the `hugchat` package: https://github.com/Soulter/hugging-chat-api/issues/206

If I update the package in `manifest.json` to `hugchat==0.4.4`, then the Login works again as expected.

**Comment by PhoenixR49** [comment]
Thanks for your report, I've just updated the extension to the latest version of `hugchat` (0.4.5).

**Comment by Sriharan-S** [comment]
> **Describe the bug** Currently, login with Hugging Face will throw an exception `Exception: Something went wrong!`
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Install the Integration (i.e. via HACS)
> 2. Add the Integration
> 3. Click Configure and Enter Credentials
> 4. Login will report wrong credentials
> 5. Logs will report `Exception: Something went wrong!`
> 
> **Expected behavior** Login should succeed
> 
> **Additional context** The reason for the Problem seems to be this issue with the `hugchat` package: [Soulter/hugging-chat-api#206](https://github.com/Soulter/hugging-chat-api/issues/206)
> 
> If I update the package in `manifest.json` to `hugchat==0.4.4`, then the Login works again as expected.

May I know, where is the manifest.json located bro?

**Comment by PhoenixR49** [comment]
What version of integration do you use?
