### ISSUE TITLE
Bug report: Trying to add Integration / Configuration fails

### ISSUE THREAD

**Issue by Sphero1337** [PhoenixR49/hass-huggingchat-conversation#8]
**Describe the bug**
When trying to add the integration after installing with HACS, i get following error:
 Config flow could not be loaded: {"message":"Invalid handler specified"} 

**To Reproduce**
1. Install via HACS from this post: https://community.home-assistant.io/t/huggingchat-integration/668518
2. Restarted Docker Container running HA
3. trying to add the integration at settings -> devices will show this mesage.
**Expected behavior**
Configuration shows up (? it's my first time trying to install this Integration)

**Environment:**
home-assistant
App Version: 2024.6.3
Chart Version: 2.0.30
Running as App in TrueNas Scale

**Comment by PhoenixR49** [comment]
Are you sure you're using the latest version of integration?

**Comment by Sphero1337** [comment]
sorry for the late response. updated Home Assistant and re-downloaded the integration, seems to work now.
