### ISSUE TITLE
Bug report: 

### ISSUE THREAD

**Issue by MrAvana** [PhoenixR49/hass-huggingchat-conversation#9]
I keep getting the error: 

Logger: root
Source: /usr/local/lib/python3.12/site-packages/hugchat/hugchat.py:733
First occurred: 6:59:39 PM (1 occurrences)
Last logged: 6:59:39 PM

No `type` found in response: {'message': 'An error occurred', 'errorId': '4f4257f0-495b-402b-811f-9142bfb3b1d9'}

Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 6:59:17 PM (2 occurrences)
Last logged: 6:59:17 PM

Detected blocking call to listdir with args ('./config/custom_components/huggingchat_conversation/cookies/',) inside the event loop by custom integration 'huggingchat_conversation' at custom_components/huggingchat_conversation/__init__.py, line 106: cookies = sign.loadCookiesFromDir(cookie_path_dir) (offender: /usr/local/lib/python3.12/site-packages/hugchat/login.py, line 212: files = os.listdir(cookie_dir_path)), please create a bug report at https://github.com/PhoenixR49/hass-huggingchat-conversation/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#listdir Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1407, in execute tts_input = await self.run.recognize_intent( File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1015, in recognize_intent conversation_result = await conversation.async_converse( File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 108, in async_converse result = await method(conversation_input) File "/config/custom_components/fallback_conversation/__init__.py", line 94, in async_process result = await self._async_process_agent( File "/config/custom_components/fallback_conversation/__init__.py", line 140, in _async_process_agent result = await agent.async_process(user_input) File "/config/custom_components/huggingchat_conversation/__init__.py", line 106, in async_process cookies = sign.loadCookiesFromDir(cookie_path_dir)
Detected blocking call to open with args ('./config/custom_components/huggingchat_conversation/cookies/avana.raveloson@gmail.com.json', 'r') inside the event loop by custom integration 'huggingchat_conversation' at custom_components/huggingchat_conversation/__init__.py, line 106: cookies = sign.loadCookiesFromDir(cookie_path_dir) (offender: /usr/local/lib/python3.12/site-packages/hugchat/login.py, line 95: with open(cookie_path, "r", encoding="utf-8") as f:), please create a bug report at https://github.com/PhoenixR49/hass-huggingchat-conversation/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1407, in execute tts_input = await self.run.recognize_intent( File "/usr/src/homeassistant/homeassistant/components/assist_pipeline/pipeline.py", line 1015, in recognize_intent conversation_result = await conversation.async_converse( File "/usr/src/homeassistant/homeassistant/components/conversation/agent_manager.py", line 108, in async_converse result = await method(conversation_input) File "/config/custom_components/fallback_conversation/__init__.py", line 94, in async_process result = await self._async_process_agent( File "/config/custom_components/fallback_conversation/__init__.py", line 140, in _async_process_agent result = await agent.async_process(user_input) File "/config/custom_components/huggingchat_conversation/__init__.py", line 106, in async_process cookies = sign.loadCookiesFromDir(cookie_path_dir)

**Comment by Bvdmgg** [comment]
I have the same issue, any solution for this?
